name: build

on:
  push:
    paths:
      - .github/workflows/*.yml
      - src/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: npm install
      - name: Export svg
        run: npm run export-svg
      - name: Export png
        run: npm run export-png
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: out
          target-folder: ./
          single-commit: true
          clean: true
